using System.Collections.Generic;
using Out.Utility;
using WoWBot.Core;

namespace WowAI
{
    internal partial class MyQuestHelpClass
    {
        public List<MyQuest> Quest612DwarfGnomeMage = new List<MyQuest>
        {
            new MyQuest(QuestAction.Grind, 7, new RoundZone(-5855.3, -145.7, 150)),
            new MyQuest(384, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(2160, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(QuestAction.SetHs, 384, new Vector3F(-5601.7, -531, 0)),
            new MyQuest(400, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(317, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(313, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(5541, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(400, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(5541, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(313, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(5541, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(317, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(317, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(384, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 7, new RoundZone(-5819.8, -238.4, 150)),
            new MyQuest(384, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(384, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(287, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(412, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(317, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(318, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(313, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(318, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(319, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(315, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(310, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(315, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(315, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(QuestAction.Grind, 9, new RoundZone(-5288.1, 366.6, 150)),
            new MyQuest(413, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(QuestAction.UseHs, 413, new Vector3F(-5378.7, 315.1, 0)),
            new MyQuest(311, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(311, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(287, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(287, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(412, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(412, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(319, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(319, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(319, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(319, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(320, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(287, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(412, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(320, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(433, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(432, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(433, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(432, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(433, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(432, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1879, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(291, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(291, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1879, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1880, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(QuestAction.SetHs, 1880, new Vector3F(-4840.9, -859, 0)),
            new MyQuest(1880, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.UseHs, 1880, new Vector3F(-5072.4, 437.3, 0)),
            new MyQuest(1880, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(419, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(419, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(417, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(417, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(417, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(413, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(414, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(224, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(267, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(224, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(224, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(267, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(224, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(267, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(414, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(416, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1339, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(QuestAction.SetHs, 1339, new Vector3F(-5378.5, -2973.5, 0)),
            new MyQuest(418, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1339, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(307, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1338, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(307, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(416, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(307, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(418, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(418, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(418, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(416, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(418, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(QuestAction.Grind, 15, new RoundZone(-5391.1, -2954.9, 350)),
//new MyQuest(246, QuestAction.UseFlyPath, "Ironforge, Dun Morogh", new Vector3F(-5424.7,-2929.9, 0)),
//new MyQuest(246, QuestAction.UseFlyPath, "Thelsamar, Loch Modan", new Vector3F(-4821.2,-1152.5, 0)),
            new MyQuest(QuestAction.GetFp, 246, new Vector3F(-3793.2, -782.3, 0)),
            new MyQuest(963, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3524, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(QuestAction.GetFp, 3524, new Vector3F(6343.3, 561.6, 0)),
            new MyQuest(QuestAction.SetHs, 3524, new Vector3F(6407.7, 518.1, 0)),
            new MyQuest(983, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(947, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4811, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(958, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(954, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(2118, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(984, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3524, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(3524, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(4681, QuestAction.Apply, ERace.None, EClass.None),
        };
    }
}