using System.Collections.Generic;
using Out.Utility;
using WoWBot.Core;

namespace WowAI
{
    internal partial class MyQuestHelpClass
    {
        public List<MyQuest> Quest1217Darkshore = new List<MyQuest>
        {
            new MyQuest(4681, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(983, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(983, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1001, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4681, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1001, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(4681, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(4723, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1001, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1002, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(954, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(955, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(955, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(955, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(956, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(956, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(956, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(957, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4811, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(984, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(953, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(953, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(957, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(953, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(963, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(958, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 14, new RoundZone(5650.8, 196.4, 150)),
            new MyQuest(953, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(2118, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.UseHs, 963, new Vector3F(5704.2, 322.8, 0)),
            new MyQuest(963, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(4811, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(4812, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4812, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(2118, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(2138, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(984, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(985, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4761, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(965, QuestAction.Apply, ERace.None, EClass.None),
            //new MyQuest(982, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4761, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(958, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(4762, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4723, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(957, QuestAction.Complete, ERace.None, EClass.None),
            //new MyQuest(982, QuestAction.Run, ERace.None, EClass.None, 0),
            //new MyQuest(982, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(4725, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1002, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1002, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1003, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4762, QuestAction.Run, ERace.None, EClass.None, 0),
            //new MyQuest(947, QuestAction.Run, ERace.None, EClass.None, 0),
            //new MyQuest(947, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(4812, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(4813, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(985, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(985, QuestAction.Run, ERace.None, EClass.None, 1),
            //new MyQuest(4722, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4728, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(2138, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1003, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1003, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(QuestAction.UseHs, 4725, new Vector3F(4815, 229.7, 0)),
            new MyQuest(4725, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(4728, QuestAction.Complete, ERace.None, EClass.None),
           // new MyQuest(4722, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1138, QuestAction.Apply, ERace.None, EClass.None),
            //new MyQuest(947, QuestAction.Complete, ERace.None, EClass.None),
            //new MyQuest(948, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4813, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(729, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4762, QuestAction.Complete, ERace.None, EClass.None),
//new MyQuest(4763, QuestAction.Apply, ERace.None, EClass.None),
            //new MyQuest(982, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(2138, QuestAction.Complete, ERace.None, EClass.None),
          //  new MyQuest(2139, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(985, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(986, QuestAction.Apply, ERace.None, EClass.None),
           // new MyQuest(2139, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(965, QuestAction.Complete, ERace.None, EClass.None),
           // new MyQuest(966, QuestAction.Apply, ERace.None, EClass.None),
           // new MyQuest(966, QuestAction.Run, ERace.None, EClass.None, 0),
           // new MyQuest(966, QuestAction.Complete, ERace.None, EClass.None),
          //  new MyQuest(967, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(4727, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1138, QuestAction.Run, ERace.None, EClass.None, 0),
//new MyQuest(4763, QuestAction.Complete, ERace.None, EClass.None),
          //  new MyQuest(2139, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(4727, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1138, QuestAction.Complete, ERace.None, EClass.None),
        };
    }
}