using System.Collections.Generic;
using Out.Utility;
using WoWBot.Core;

namespace WowAI
{
    internal partial class MyQuestHelpClass
    {
//

        public List<MyQuest> Quest1012UndeadWarrior = new List<MyQuest>
        {
            new MyQuest(1818, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(359, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(356, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(360, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(356, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(356, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(371, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(371, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(369, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(356, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(371, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(360, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(369, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(445, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(492, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1818, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1819, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1819, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1819, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1820, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1820, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1821, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1821, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1821, QuestAction.Run, ERace.None, EClass.None, 3),
            new MyQuest(1821, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(1821, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(408, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(408, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1821, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1822, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1822, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(492, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(372, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(374, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 11, new RoundZone(3076.7, -556.1, 150)),
            new MyQuest(374, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Complete, ERace.None, EClass.None),
        };

        public List<MyQuest> Quest1012UndeadWarlock = new List<MyQuest>
        {
            new MyQuest(1478, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(405, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1478, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1473, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(405, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1473, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1473, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1471, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1471, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1471, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(359, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(356, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(360, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(356, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(356, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(371, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(371, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(369, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(356, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(371, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(360, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(369, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(445, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(492, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(408, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(408, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(492, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(372, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(374, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 11, new RoundZone(3076.7, -556.1, 150)),
            new MyQuest(374, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Complete, ERace.None, EClass.None),
        };

        public List<MyQuest> Quest1012UndeadRogue = new List<MyQuest>
        {
            new MyQuest(1885, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(405, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1885, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1886, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(405, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1886, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1886, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1898, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1898, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1899, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1899, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1899, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1978, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1978, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(359, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(356, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(360, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(356, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(356, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(371, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(371, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(369, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(356, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(371, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(360, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(369, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(445, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(492, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(408, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(408, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(492, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(372, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(374, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 11, new RoundZone(3076.7, -556.1, 150)),
            new MyQuest(374, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Complete, ERace.None, EClass.None),
        };

        public List<MyQuest> Quest1012UndeadMage = new List<MyQuest>
        {
            new MyQuest(1881, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(405, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(405, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1881, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1882, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(359, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(356, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(360, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1882, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(356, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(356, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(371, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(371, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(369, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(356, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(371, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(360, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(369, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(445, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(492, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(408, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(408, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(492, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(372, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(374, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 11, new RoundZone(3076.7, -556.1, 150)),
            new MyQuest(1882, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(374, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(372, QuestAction.Complete, ERace.None, EClass.None),
        };

        //

        public List<MyQuest> Quest112TaurenWarrior = new List<MyQuest>
        {
            new MyQuest(747, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(747, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(747, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(747, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(750, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3091, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3091, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(752, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(752, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(753, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(753, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(753, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(755, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(755, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(757, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(750, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(750, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(780, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3376, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3376, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(781, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(757, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(780, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(780, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(780, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(3376, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(757, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(781, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(763, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1656, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(QuestAction.Grind, 6, new RoundZone(-2397.4, -384.5, 150)),
            new MyQuest(743, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1656, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(763, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(745, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(767, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(746, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(761, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(748, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(767, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(771, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(766, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(771, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(771, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(745, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(745, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(745, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(743, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(749, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(749, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(751, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(748, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(748, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 3),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(745, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(743, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(748, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(754, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(771, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(772, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(766, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(751, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(765, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(764, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(754, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(754, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(756, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(772, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(773, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(833, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(773, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(775, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(833, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(833, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(756, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(756, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(761, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 10, new RoundZone(-1710, -327.4, 150)),
            new MyQuest(861, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(756, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(758, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(761, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1505, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(758, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(744, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(746, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(775, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(776, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(765, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(764, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(764, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(758, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(759, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(746, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(765, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(764, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(744, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(744, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(759, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(861, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(886, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(861, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(860, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(744, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(759, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(760, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(760, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 12, new RoundZone(-2341.5, -445.5, 150)),
            new MyQuest(760, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(854, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(886, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(870, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(860, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(844, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(869, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(854, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(871, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(5041, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(867, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1492, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(848, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(6361, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(6361, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(6362, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1505, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1498, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1498, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(840, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(840, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(842, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1498, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1502, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1502, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1503, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1503, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(819, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(871, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(871, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(871, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(1503, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(842, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(871, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(872, QuestAction.Apply, ERace.None, EClass.None),
        };

        public List<MyQuest> Quest112TaurenShaman = new List<MyQuest>
        {
            new MyQuest(747, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(747, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(747, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(747, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(750, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3093, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3093, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(752, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(752, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(753, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(753, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(753, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(755, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(755, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(757, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(750, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(750, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(780, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3376, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(QuestAction.Grind, 4, new RoundZone(-2907.2, -257.9, 150)),
            new MyQuest(1519, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3376, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(781, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(757, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1519, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(780, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(780, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(780, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(3376, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1519, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1520, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(757, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(781, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(763, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1520, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1521, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1521, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1656, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(QuestAction.Grind, 6, new RoundZone(-2397.4, -384.5, 150)),
            new MyQuest(743, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1656, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(763, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(745, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(767, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(746, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(761, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(748, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(767, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(771, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(766, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(771, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(771, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(745, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(745, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(745, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(743, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(749, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(749, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(751, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(748, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(748, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 3),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(745, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(743, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(748, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(754, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(771, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(772, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(766, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(751, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(765, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(764, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(754, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(754, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(756, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(772, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(773, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(833, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(773, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(775, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(833, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(833, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(756, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(756, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(761, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 10, new RoundZone(-1710, -327.4, 150)),
            new MyQuest(861, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(756, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(758, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(761, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(2984, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(758, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(744, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(746, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(775, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(776, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(765, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(764, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(764, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(758, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(759, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(746, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(765, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(764, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(744, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(744, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(759, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(861, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(886, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(861, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(860, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(744, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(759, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(760, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(760, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 12, new RoundZone(-2341.5, -445.5, 150)),
            new MyQuest(760, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(854, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(886, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(870, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(860, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(844, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(869, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(854, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(871, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(5041, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(867, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1492, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(848, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(6361, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(6361, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(6362, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(2984, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1524, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1524, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1525, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(840, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1525, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(819, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(871, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(871, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(871, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(1525, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1525, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1526, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1526, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(1526, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(1527, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(840, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(842, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1527, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(842, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(871, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(872, QuestAction.Apply, ERace.None, EClass.None),
        };

        public List<MyQuest> Quest112TaurenHunter = new List<MyQuest>
        {
            new MyQuest(747, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(747, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(747, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(747, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(750, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3092, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3092, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(752, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(752, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(753, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(753, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(753, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(755, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(755, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(757, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(750, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(750, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(780, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3376, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(3376, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(781, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(757, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(780, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(780, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(780, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(3376, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(757, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(781, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(763, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1656, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(QuestAction.Grind, 6, new RoundZone(-2397.4, -384.5, 150)),
            new MyQuest(743, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1656, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(763, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(745, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(767, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(746, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(761, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(748, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(767, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(771, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(766, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(771, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(771, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(745, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(745, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(745, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(743, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(749, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(749, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(751, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(748, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(748, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 3),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(766, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(745, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(743, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(748, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(754, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(771, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(772, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(766, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(751, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(765, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(764, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(754, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(754, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(756, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(772, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(773, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(833, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(773, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(775, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(833, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(833, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(756, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(756, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(761, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 10, new RoundZone(-1710, -327.4, 150)),
            new MyQuest(861, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(756, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(758, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(761, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(6061, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(6061, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(6061, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(6087, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(6087, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(6087, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(6088, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(6088, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(6088, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(6089, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(758, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(744, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(746, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(6089, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(775, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(776, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(765, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(764, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(764, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(758, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(759, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(746, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(765, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(764, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(744, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(744, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(759, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(861, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(886, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(861, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(860, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(744, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(759, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(760, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(760, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(QuestAction.Grind, 12, new RoundZone(-2341.5, -445.5, 150)),
            new MyQuest(760, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(854, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(886, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(870, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(860, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(844, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(869, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(854, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(871, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(5041, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(867, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(1492, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(848, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(6361, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(6361, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(6362, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(819, QuestAction.Apply, ERace.None, EClass.None),
            new MyQuest(871, QuestAction.Run, ERace.None, EClass.None, 0),
            new MyQuest(871, QuestAction.Run, ERace.None, EClass.None, 2),
            new MyQuest(871, QuestAction.Run, ERace.None, EClass.None, 1),
            new MyQuest(871, QuestAction.Complete, ERace.None, EClass.None),
            new MyQuest(872, QuestAction.Apply, ERace.None, EClass.None),
        };

        //LuaD:\WowShare\16GotoTB-Tauren.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest16GotoTbTauren = new List<MyQuest>
{
new MyQuest(4921, QuestAction.UseFlyPath, "Thunder Bluff, Mulgore", new Vector3F(-2384.1,-1881.6, 0)),
new MyQuest(853, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(4921, QuestAction.Complete, ERace.None, EClass.None),
};

        //LuaD:\WowShare\20-TB-Prep.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest20TbPrep = new List<MyQuest>
{
new MyQuest(3281, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(905, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(3261, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(899, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(880, QuestAction.Complete, ERace.None, EClass.None),
//new MyQuest(6382, QuestAction.UseFlyPath, "Thunder Bluff, Mulgore", new Vector3F(-437.5,-2596.3, 0)),
//new MyQuest(6382, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(821, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(821, QuestAction.UseFlyPath, "Ratchet, The Barrens", new Vector3F(-437.4,-2595.8, 0)),
new MyQuest(865, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1069, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(821, QuestAction.Complete, ERace.None, EClass.None),
//new MyQuest(822, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(891, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(891, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(891, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(891, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(891, QuestAction.Run, ERace.None, EClass.None,3),
new MyQuest(891, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(852, QuestAction.UseFlyPath, "Crossroads, The Barrens", new Vector3F(-898.5,-3769.7, 0)),
new MyQuest(852, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1060, QuestAction.Complete, ERace.None, EClass.None),
};
        //LuaD:\WowShare\20-23Ashenvale-SouthBarrens.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest2023AshenvaleSouthBarrens = new List<MyQuest>
{
new MyQuest(1060, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1058, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6461, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6284, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6461, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6461, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(1483, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1093, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1093, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1062, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1069, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1093, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1094, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6282, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6301, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6562, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6421, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6421, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(6421, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6461, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1062, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6562, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6442, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6442, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(QuestAction.Grind, 22, new RoundZone(3787.1, 858.5, 150)),
new MyQuest(6442, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(868, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(868, QuestAction.UseFlyPath, "Camp Taurajo, The Barrens", new Vector3F(-437.4,-2596.4, 0)),
new MyQuest(868, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(879, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(879, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(879, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(893, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(893, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(893, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(843, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(843, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(843, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(843, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(843, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(846, QuestAction.Apply, ERace.None, EClass.None),
//new MyQuest(822, QuestAction.Run, ERace.None, EClass.None,0),
//new MyQuest(822, QuestAction.Run, ERace.None, EClass.None,2),
//new MyQuest(822, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(QuestAction.Grind, 22, new RoundZone(-3481, -2053.2, 150)),
new MyQuest(3261, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(882, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1130, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(893, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(879, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(906, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(868, QuestAction.UseFlyPath, "Crossroads, The Barrens", new Vector3F(-2383.9,-1881.7, 0)),
new MyQuest(906, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(868, QuestAction.Complete, ERace.None, EClass.None),
};
        //LuaD:\WowShare\23-25StonetalonMountains.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest2325StonetalonMountains = new List<MyQuest>
{
new MyQuest(882, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1069, QuestAction.Complete, ERace.None, EClass.None),
//new MyQuest(822, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1094, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1095, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6421, QuestAction.UseFlyPath, "Sun Rock Retreat, Stonetalon Mountains", new Vector3F(-898.6,-3769.9, 0)),
new MyQuest(1087, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6282, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6301, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6421, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6393, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6301, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1058, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1058, QuestAction.Run, ERace.None, EClass.None,3),
new MyQuest(1058, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(1058, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(1087, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1087, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(1087, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(1095, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1096, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1068, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(1068, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1096, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1096, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(QuestAction.Grind, 24, new RoundZone(982.6, -359.9, 150)),
new MyQuest(1058, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1068, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6301, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6381, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1087, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1088, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6381, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6282, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6282, QuestAction.Run, ERace.None, EClass.None,3),
new MyQuest(6282, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(6282, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(6393, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6393, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6282, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5881, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6381, QuestAction.Complete, ERace.None, EClass.None),
};
        //LuaD:\WowShare\25-SouthernBarrens.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest25SouthernBarrens = new List<MyQuest>
{
new MyQuest(882, QuestAction.UseFlyPath, "Thunder Bluff, Mulgore", new Vector3F(968.3,1042.4, 0)),
new MyQuest(1195, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1130, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1131, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(882, QuestAction.UseFlyPath, "Camp Taurajo, The Barrens", new Vector3F(-1197,26.3, 0)),
new MyQuest(882, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(907, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1153, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(907, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(857, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(857, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(857, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(846, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(846, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(846, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(846, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(849, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(849, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(849, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5881, QuestAction.Complete, ERace.None, EClass.None),
};
        //LuaD:\WowShare\25-26ThousandNeedles.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest2526ThousandNeedles = new List<MyQuest>
{
new MyQuest(4542, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(4542, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(4841, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5147, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(4767, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(4821, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(4841, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(4841, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(4841, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(1149, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1149, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(4821, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(QuestAction.Grind, 25, new RoundZone(-5438, -2540.3, 150)),
new MyQuest(4841, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5064, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(4821, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(4865, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(907, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(913, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(913, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(913, QuestAction.Complete, ERace.None, EClass.None),
};
        //LuaD:\WowShare\26-28Ashenvale.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest2628Ashenvale = new List<MyQuest>
{
new MyQuest(6441, QuestAction.UseFlyPath, "Splintertree Post, Ashenvale", new Vector3F(-2383.9,-1881.4, 0)),
new MyQuest(6441, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(25, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6503, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(2, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6503, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6544, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6544, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1918, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(25, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(25, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(23, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(24, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1195, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(2, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(23, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(24, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(247, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(247, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1918, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(25, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(824, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6544, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(824, QuestAction.UseFlyPath, "Zoram'gar Outpost, Ashenvale", new Vector3F(2304.9,-2520.1, 0)),
new MyQuest(824, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6462, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(216, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6641, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6641, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(216, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(216, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(6462, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(216, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6641, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6462, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6503, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1088, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6441, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6441, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6283, QuestAction.UseFlyPath, "Sun Rock Retreat, Stonetalon Mountains", new Vector3F(2305.9,-2520.5, 0)),
new MyQuest(1088, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6283, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6283, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6283, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1195, QuestAction.UseFlyPath, "Thunder Bluff, Mulgore", new Vector3F(968,1042.5, 0)),
new MyQuest(1195, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1196, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1196, QuestAction.UseFlyPath, "Freewind Post, Thousand Needles", new Vector3F(-1196.7,26.1, 0)),
new MyQuest(1196, QuestAction.Complete, ERace.None, EClass.None),
};
        //LuaD:\WowShare\28-30TN-Hillsbrad.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest2830TnHillsbrad = new List<MyQuest>
{
new MyQuest(1197, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1197, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(4865, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5062, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5151, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5062, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1131, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(4767, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(4770, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(4770, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1131, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1136, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5062, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5088, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(4767, QuestAction.UseFlyPath, "Freewind Post, Thousand Needles", new Vector3F(-1196.7,26, 0)),
new MyQuest(4767, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1197, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5064, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(5064, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(5064, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(5088, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(5088, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(5147, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(4904, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(4904, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(5088, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(4770, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5151, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(QuestAction.Grind, 29, new RoundZone(-4619.8, -1255, 150)),
new MyQuest(4904, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5064, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5147, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(496, QuestAction.UseFlyPath, "Orgrimmar, Durotar", new Vector3F(-5407.4,-2419.6, 0)),
new MyQuest(496, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(509, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(501, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(527, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(552, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(567, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(509, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(501, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(496, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(496, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(496, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(509, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(501, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(502, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(499, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(499, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(7321, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(7321, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(7321, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(7321, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(552, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(552, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(553, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(553, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(553, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(502, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(527, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(567, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(527, QuestAction.Run, ERace.None, EClass.None,3),
new MyQuest(567, QuestAction.Run, ERace.None, EClass.None,3),
new MyQuest(527, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(527, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(567, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(567, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(QuestAction.Grind, 29, new RoundZone(-842.1, 94.5, 150)),
new MyQuest(567, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(527, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1361, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(655, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(655, QuestAction.Complete, ERace.None, EClass.None),
};
        //LuaD:\WowShare\30-Arathi-STV.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest30ArathiStv = new List<MyQuest>
{
new MyQuest(672, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(672, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(672, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(674, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(674, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(675, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(675, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(583, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(583, QuestAction.Complete, ERace.None, EClass.None),
};




        //LuaD:\WowShare\30-32STV-TN.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest3032StvTn = new List<MyQuest>
{
new MyQuest(194, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(185, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(190, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(185, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(185, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(186, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(190, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(186, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(190, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(186, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(191, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(187, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(191, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(194, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(191, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(194, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(195, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(192, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(QuestAction.Grind, 31, new RoundZone(-11617.7, -48.4, 150)),
new MyQuest(1361, QuestAction.UseFlyPath, "Crossroads, The Barrens", new Vector3F(1676.3,-4313.9, 0)),
new MyQuest(1145, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1361, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1362, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1110, QuestAction.UseFlyPath, "Freewind Post, Thousand Needles", new Vector3F(-437.2,-2595.7, 0)),
new MyQuest(1110, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1104, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1105, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1176, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1175, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1104, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1105, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1176, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1110, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1175, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1175, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(1175, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(1110, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5762, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1111, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1104, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1105, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1176, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1178, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1175, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(QuestAction.Grind, 32, new RoundZone(-6253, -4025.4, 150)),
new MyQuest(1145, QuestAction.UseFlyPath, "Freewind Post, Thousand Needles", new Vector3F(-7045.1,-3779.4, 0)),
new MyQuest(5361, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1145, QuestAction.Complete, ERace.None, EClass.None),
};
        //LuaD:\WowShare\32-34Desolace.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest3234Desolace = new List<MyQuest>
{
new MyQuest(1146, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1431, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1431, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1432, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1362, QuestAction.UseFlyPath, "Sun Rock Retreat, Stonetalon Mountains", new Vector3F(1676.4,-4313.5, 0)),
new MyQuest(5561, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5561, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(5561, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1362, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1365, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1368, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5361, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1432, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1433, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1434, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1433, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1435, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1365, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1368, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1365, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1366, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1368, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1370, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5763, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5381, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6143, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6142, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6161, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5741, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5741, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(5381, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1435, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1480, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1480, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1435, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1481, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5386, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5386, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1481, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1434, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1434, QuestAction.Run, ERace.None, EClass.None,3),
new MyQuest(1434, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(1434, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(5501, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1434, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1436, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1481, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1482, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(5741, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6027, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6142, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6161, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6027, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6161, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(6161, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1482, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6143, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(6143, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(6143, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(6027, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1482, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1484, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1484, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5501, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1370, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1366, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1366, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5501, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5381, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1370, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1373, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(6143, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(6142, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1178, QuestAction.UseFlyPath, "Camp Taurajo, The Barrens", new Vector3F(-1770.3,3261.9, 0)),
new MyQuest(1268, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1269, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1251, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1268, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1269, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1251, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1321, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1321, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1178, QuestAction.UseFlyPath, "Ratchet, The Barrens", new Vector3F(-3149.7,-2842.3, 0)),
new MyQuest(1178, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1180, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1111, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1112, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1180, QuestAction.Complete, ERace.None, EClass.None),
};
        //LuaD:\WowShare\34-37.json ------------------QuestInfo-----------------------
        public List<MyQuest> Quest3437 = new List<MyQuest>
{
new MyQuest(1181, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(605, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(201, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(189, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(213, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(1181, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1182, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(575, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(605, QuestAction.UseFlyPath, "Grom'gol, Stranglethorn", new Vector3F(-14448.5,506.9, 0)),
new MyQuest(568, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(570, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(596, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(189, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(581, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(187, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(568, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(195, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(581, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(582, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(568, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(569, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(582, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(596, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(5763, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(195, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(187, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(5762, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(188, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(196, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(192, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(188, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(188, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(575, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1182, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(213, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(570, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(570, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(192, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(605, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(569, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(569, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(192, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(193, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(605, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(201, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(213, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(189, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1182, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(1183, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(575, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(577, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(569, QuestAction.UseFlyPath, "Grom'gol, Stranglethorn", new Vector3F(-14448.4,506.2, 0)),
new MyQuest(569, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(570, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(582, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(596, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(638, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(QuestAction.Grind, 36, new RoundZone(-12347.8, 165, 150)),
new MyQuest(1164, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(638, QuestAction.UseFlyPath, "Tarren Mill, Hillsbrad", new Vector3F(1566.7,265.6, 0)),
new MyQuest(676, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(638, QuestAction.UseFlyPath, "Hammerfall, Arathi", new Vector3F(2.4,-858, 0)),
new MyQuest(638, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(639, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(701, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(671, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(642, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(642, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(642, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(651, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(651, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(1164, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(1164, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(1164, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(651, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(701, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(676, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(676, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(671, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(651, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(639, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(651, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(652, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(639, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(676, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(677, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(701, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(671, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(702, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(702, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(847, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(847, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(677, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(677, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(677, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(677, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(678, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(678, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(678, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(QuestAction.Grind, 37, new RoundZone(-1956.1, -2763.5, 150)),
new MyQuest(678, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(680, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(680, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(640, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(673, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(679, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(679, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(680, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(640, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(679, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(673, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(544, QuestAction.UseFlyPath, "Tarren Mill, Hillsbrad", new Vector3F(-918,-3497.7, 0)),
new MyQuest(544, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(556, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(553, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(1136, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(556, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(544, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(544, QuestAction.Run, ERace.None, EClass.None,3),
new MyQuest(544, QuestAction.Run, ERace.None, EClass.None,2),
new MyQuest(544, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(553, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(556, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(544, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(545, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(557, QuestAction.Apply, ERace.None, EClass.None),
new MyQuest(557, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(545, QuestAction.Run, ERace.None, EClass.None,0),
new MyQuest(545, QuestAction.Run, ERace.None, EClass.None,1),
new MyQuest(557, QuestAction.Complete, ERace.None, EClass.None),
new MyQuest(545, QuestAction.Complete, ERace.None, EClass.None),
};



    }
}
